#!/bin/bash

echo "========================================="
echo "프로덕션 환경 설정 가이드"
echo "========================================="
echo ""
echo "📊 데이터베이스 설정 (선택 1: Neon PostgreSQL)"
echo "----------------------------------------"
echo "1. https://neon.tech 접속 및 가입"
echo "2. 새 프로젝트 생성"
echo "3. Connection String 복사"
echo "4. Vercel 환경변수에 추가:"
echo "   DATABASE_URL=postgresql://..."
echo "   DATABASE_URL_UNPOOLED=postgresql://..."
echo ""
echo "📊 데이터베이스 설정 (선택 2: Supabase)"
echo "----------------------------------------"
echo "1. https://supabase.com 접속 및 가입"
echo "2. 새 프로젝트 생성"
echo "3. Settings > Database에서 Connection String 복사"
echo "4. Vercel 환경변수에 추가"
echo ""
echo "🔧 Prisma 스키마 업데이트"
echo "----------------------------------------"
cat > prisma/schema.prisma.production << 'EOF'
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
  directUrl = env("DATABASE_URL_UNPOOLED")
}
EOF
echo "✅ prisma/schema.prisma.production 파일 생성됨"
echo ""
echo "🚀 Vercel 배포 설정"
echo "----------------------------------------"
echo "1. https://vercel.com 접속"
echo "2. Import Git Repository"
echo "3. Environment Variables 설정:"
echo ""
echo "필수 환경변수:"
echo "=============="
echo "# Database"
echo "DATABASE_URL=(PostgreSQL URL)"
echo "DATABASE_URL_UNPOOLED=(Direct PostgreSQL URL)"
echo ""
echo "# NextAuth"
echo "NEXTAUTH_SECRET=(openssl rand -base64 32 로 생성)"
echo "NEXTAUTH_URL=https://your-domain.vercel.app"
echo ""
echo "# 결제 (토스페이먼츠)"
echo "NEXT_PUBLIC_TOSS_CLIENT_KEY=(클라이언트 키)"
echo "TOSS_SECRET_KEY=(시크릿 키)"
echo ""
echo "# 이메일 (SendGrid 또는 SMTP)"
echo "EMAIL_PROVIDER=sendgrid"
echo "SENDGRID_API_KEY=(SendGrid API 키)"
echo "EMAIL_FROM=noreply@your-domain.com"
echo ""
echo "# 또는 SMTP 설정"
echo "EMAIL_PROVIDER=smtp"
echo "SMTP_HOST=smtp.gmail.com"
echo "SMTP_PORT=587"
echo "SMTP_USER=(이메일 주소)"
echo "SMTP_PASS=(앱 비밀번호)"
echo ""
echo "# Google Vision API (선택)"
echo "GOOGLE_VISION_API_KEY=(Base64 인코딩된 서비스 계정 키)"
echo "GOOGLE_CLOUD_PROJECT_ID=(프로젝트 ID)"
echo ""
echo "🔍 배포 전 체크리스트"
echo "----------------------------------------"
echo "✅ TypeScript 컴파일 에러 해결"
echo "✅ 로컬 환경에서 모든 기능 테스트"
echo "✅ 환경변수 모두 설정"
echo "✅ 데이터베이스 마이그레이션 실행"
echo "✅ 빌드 테스트 (npm run build)"
echo ""
echo "📝 배포 명령어"
echo "----------------------------------------"
echo "# Vercel CLI 설치"
echo "npm i -g vercel"
echo ""
echo "# 배포"
echo "vercel --prod"
echo ""
echo "========================================="