name: CI

on:
  push:
    branches: [ main, stabilize/**, fix/**, feat/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build
        env:
          NEXTAUTH_SECRET: test_secret
          NEXTAUTH_URL: http://localhost:3000
          DATABASE_URL: file:./prisma/dev.db
        run: npm run build

